<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\PdfDatos;


class PdfDatosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        PdfDatos::create([
            'img_principal' => '/pdfdatos/presentacion2.png',
            'ruc'           => '20600769317',
            'razon_social'  => 'AVT CUZCO TRAVEL EIRL',
            'rec_cancel1'   => '<p><strong>Estimado viajero,</strong></p> <p>Reciba un cordial saludo de todo el equipo de CUZCO TRAVEL. Nos llena de entusiasmo que haya seleccionado nuestra compa&ntilde;&iacute;a como su aliada en la exploraci&oacute;n de las maravillas del Per&uacute;. Nos comprometemos a proporcionarle una experiencia inolvidable, llena de descubrimientos y aventuras.</p> <p></p> <p><strong>Proceso de Reserva y Pol&iacute;ticas de Pago:</strong></p> <p></p> <p>Dep&oacute;sito de Reserva: Para asegurar su lugar en esta emocionante traves&iacute;a, requerimos un dep&oacute;sito inicial del 60% del costo total del tour. Este paso es esencial para la reserva de boletos y servicios adicionales, asegurando la disponibilidad y una planificaci&oacute;n detallada de su viaje.</p> <p></p> <p>Liquidaci&oacute;n del Saldo: El saldo restante debe ser pagado d&iacute;as antes de su llegada a Per&uacute;. Ofrecemos flexibilidad en los m&eacute;todos de pago, permitiendo el uso de tarjeta de cr&eacute;dito (con un recargo adicional del 6.5% por comisi&oacute;n) o en efectivo, de acuerdo a su conveniencia.</p> <p></p> <p><strong>Pol&iacute;tica de Cancelaci&oacute;n y Modificaciones:</strong></p> <p></p> <p>Derecho de Cancelaci&oacute;n: CUZCO TRAVEL se reserva el derecho de cancelar cualquier viaje debido a circunstancias excepcionales o imprevistas. Nos comprometemos a comunicar cualquier cambio con la mayor antelaci&oacute;n posible y a ofrecer alternativas adecuadas para reacomodar su experiencia.</p> <p></p> <p>No Reembolso por Gastos Anticipados: Es importante que tenga en cuenta que no nos hacemos responsables por gastos incurridos antes de la confirmaci&oacute;n oficial de su viaje, tales como boletos a&eacute;reos no reembolsables, tr&aacute;mites de visa, o gastos m&eacute;dicos.</p> <p></p> <p>Pol&iacute;tica de No Reembolso: Si decide cancelar o no asistir a un viaje de varios d&iacute;as, recuerde que el dep&oacute;sito inicial del 50% no es reembolsable y no transferible. Esto refleja nuestra pol&iacute;tica de no cancelaci&oacute;n y asegura que los arreglos log&iacute;sticos y preparativos realizados no resulten en una p&eacute;rdida financiera para nuestra empresa.</p>',
            'rec_cancel2'   => '<p><strong>Cambios en la Reserva:</strong></p> <p>&nbsp;</p> <p>Cambios Planificados: Si necesita cambiar la fecha o la ruta de su viaje (con la excepci&oacute;n del tour a Machu Picchu), y lo hace con m&aacute;s de 56 horas de antelaci&oacute;n al inicio del tour, se aplicar&aacute; una tarifa administrativa de US$ 50.00 por persona.</p> <p>&nbsp;</p> <p>Cambios de &Uacute;ltimo Minuto: Para los cambios solicitados dentro de las 48 horas previas al inicio del tour, se aplicar&aacute; una tarifa de US$ 100.00 por persona.</p> <p>&nbsp;</p> <p><strong>Condiciones Espec&iacute;ficas en Cusco:</strong></p> <p>&nbsp;</p> <p>Log&iacute;stica de Transporte: Teniendo en cuenta las calles estrechas y el encanto &uacute;nico de Cusco, es posible que el servicio de recojo se realice en puntos de encuentro estrat&eacute;gicos y accesibles, en lugar de directamente en su hotel.</p> <p>&nbsp;</p> <p><strong>Documentos y Comunicaciones Importantes:</strong></p> <p>&nbsp;</p> <p>Documentaci&oacute;n Adjunta: Junto a este comunicado, encontrar&aacute; su programa de viaje detallado e informaci&oacute;n adicional que incluye consejos pr&aacute;cticos y recomendaciones para una experiencia de viaje m&aacute;s placentera.</p> <p>&nbsp;</p> <p>Comprobante de Pago y Coordinaci&oacute;n: Recibir&aacute; un comprobante de pago desde facturacion@cuscoinsight.com y nuestro equipo de operaciones se contactar&aacute; con usted para finalizar detalles y manejar el saldo pendiente.</p>',
            'poli_ven1'     => '<p><strong>Recomendaciones y Consejos de Viaje:</strong></p> <p>&nbsp;</p> <p>Alojamiento: Le sugerimos optar por alojamientos cerca de la Plaza de Armas en Cusco y en el distrito de Miraflores en Lima, para facilitar los traslados y el acceso a actividades programadas.</p> <p>&nbsp;&nbsp;</p> <p>Preparativos de Viaje: Por favor, aseg&uacute;rese de enviarnos los detalles de sus vuelos y cualquier documento adicional que se haya solicitado, como pasaportes o identificaciones.</p> <p>&nbsp;</p> <p><strong>Puntos a Recordar:</strong></p> <p>&nbsp;</p> <p>Admisiones a Sitios Tur&iacute;sticos: A menos que se especifique lo contrario en su itinerario, los ingresos a sitios tur&iacute;sticos no est&aacute;n incluidos, excepto para Machu Picchu siempre y cuando lo haya contratado de esta manera.</p> <p>&nbsp;</p> <p>Din&aacute;mica de los Tours: A menos que haya contratado un tour privado, participar&aacute; en tours Grupos compartidos con un m&aacute;ximo de 20 pasajeros, proporcionando una experiencia rica y din&aacute;mica con gu&iacute;as expertos en espa&ntilde;ol. Para los tours privados, disfrutar&aacute; de una atenci&oacute;n personalizada y un itinerario ajustado a sus preferencias personales.</p> <p>&nbsp;</p> <p>Retorno y Horarios: Tras cada excursi&oacute;n, el retorno es al centro de Cusco, salvo en el caso del tour a Machu Picchu, donde garantizamos el traslado de regreso a su hotel. Los horarios de trenes y entradas a Machu Picchu se sujetan a la disponibilidad y ser&aacute;n confirmados con antelaci&oacute;n, procurando siempre la mejor experiencia.</p>',
            'poli_ven2'     => '<p><strong>Seguros de Viaje:</strong></p> <p>Recomendamos encarecidamente la contrataci&oacute;n de un seguro de viaje completo que cubra eventualidades m&eacute;dicas, cancelaciones y otras interrupciones. Esto no solo es una medida de precauci&oacute;n, sino tambi&eacute;n una inversi&oacute;n en su tranquilidad durante su aventura en Per&uacute;.</p> <p>&nbsp;</p> <p><strong>Compromiso de CUZCO TRAVEL:</strong></p> <p>Nuestro compromiso es con su satisfacci&oacute;n y seguridad. Nuestro equipo est&aacute; dedicado a manejar todos los aspectos de su viaje con profesionalismo y cuidado, y estamos disponibles para responder a cualquier consulta o necesidad que pueda surgir antes o durante su viaje.</p> <p>&nbsp;</p> <p>Le agradecemos su confianza en CUZCO TRAVEL y nos entusiasma poder ofrecerle una experiencia de viaje que supere sus expectativas. Estamos seguros de que su aventura en Per&uacute; ser&aacute; una historia que atesorar&aacute; por siempre.</p> <p>&nbsp;</p> <p>Si tiene preguntas adicionales o necesita m&aacute;s informaci&oacute;n, no dude en contactarnos. &iexcl;Esperamos darle la bienvenida pronto y ser parte de su inolvidable viaje por Per&uacute;!</p>',
            'poli_nota'     => 'Para más información detallada sobre las politicas de venta de CUZCO TRAVEL por favor revisar el documento de politicas de venta que vendra anexado con su confirmación de viaje o solicitarlo a su ejecutiva de ventas.',
        ]);
    }
}

